FROM rocker/r-ver:4.0.2
RUN apt-get update && apt-get install -y  git-core imagemagick libcairo2-dev libcurl4-openssl-dev libgit2-dev libgl1-mesa-dev libglu1-mesa-dev libmagic-dev libmagick++-dev libpng-dev libssh2-1-dev libssl-dev libxml2-dev make pandoc pandoc-citeproc zlib1g-dev && rm -rf /var/lib/apt/lists/*
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN Rscript -e 'remotes::install_version("config",upgrade="never", version = "0.3")'
RUN Rscript -e 'remotes::install_version("shiny",upgrade="never", version = "1.5.0")'
RUN Rscript -e 'remotes::install_version("htmltools",upgrade="never", version = "0.5.0")'
RUN Rscript -e 'remotes::install_version("ggplot2",upgrade="never", version = "3.3.2")'
RUN Rscript -e 'remotes::install_version("SpATS",upgrade="never", version = "1.0-11")'
RUN Rscript -e 'remotes::install_version("shinyjs",upgrade="never", version = "1.1")'
RUN Rscript -e 'remotes::install_version("rintrojs",upgrade="never", version = "0.2.2")'
RUN Rscript -e 'remotes::install_version("shinytoastr",upgrade="never", version = "2.1.1")'
RUN Rscript -e 'remotes::install_version("shinyalert",upgrade="never", version = "1.1")'
RUN Rscript -e 'remotes::install_version("thinkr",upgrade="never", version = "0.15")'
RUN Rscript -e 'remotes::install_version("attempt",upgrade="never", version = "0.3.1")'
RUN Rscript -e 'remotes::install_version("DT",upgrade="never", version = "0.14")'
RUN Rscript -e 'remotes::install_version("glue",upgrade="never", version = "1.4.1")'
RUN Rscript -e 'remotes::install_version("processx",upgrade="never", version = "3.4.3")'
RUN Rscript -e 'remotes::install_version("pkgload",upgrade="never", version = "1.1.0")'
RUN Rscript -e 'remotes::install_version("dplyr",upgrade="never", version = "1.0.0")'
RUN Rscript -e 'remotes::install_version("shinycssloaders",upgrade="never", version = "0.3")'
RUN Rscript -e 'remotes::install_version("plotly",upgrade="never", version = "4.9.2.1")'
RUN Rscript -e 'remotes::install_version("summarytools",upgrade="never", version = "0.9.6")'
RUN Rscript -e 'remotes::install_version("ggpubr",upgrade="never", version = "0.4.0")'
RUN Rscript -e 'remotes::install_version("lme4",upgrade="never", version = "1.1-23")'
RUN Rscript -e 'remotes::install_version("yaml",upgrade="never", version = "2.2.1")'
RUN Rscript -e 'remotes::install_version("magrittr",upgrade="never", version = "1.5")'
RUN Rscript -e 'remotes::install_version("echarts4r",upgrade="never", version = "0.3.2")'
RUN Rscript -e 'remotes::install_version("data.table",upgrade="never", version = "1.12.8")'
RUN Rscript -e 'remotes::install_version("tidyr",upgrade="never", version = "1.1.0")'
RUN Rscript -e 'remotes::install_version("readxl",upgrade="never", version = "1.3.1")'
RUN Rscript -e 'remotes::install_version("kableExtra",upgrade="never", version = "1.1.0")'
RUN Rscript -e 'remotes::install_version("formattable",upgrade="never", version = "0.2.0.1")'
RUN Rscript -e 'remotes::install_version("tibble",upgrade="never", version = "3.0.3")'
RUN Rscript -e 'remotes::install_version("reshape",upgrade="never", version = "0.8.8")'
RUN Rscript -e 'remotes::install_version("factoextra",upgrade="never", version = "1.0.7")'
RUN Rscript -e 'remotes::install_version("sever",upgrade="never", version = "0.0.4")'
RUN Rscript -e 'remotes::install_version("geoR",upgrade="never", version = "1.8-1")'
RUN Rscript -e 'remotes::install_version("psych",upgrade="never", version = "1.9.12.31")'
RUN Rscript -e 'remotes::install_version("lmerTest",upgrade="never", version = "3.1-2")'
RUN Rscript -e 'remotes::install_version("broom.mixed",upgrade="never", version = "0.2.6")'
RUN Rscript -e 'remotes::install_version("testthat",upgrade="never", version = "2.3.2")'
RUN Rscript -e 'remotes::install_github("Thinkr-open/golem@d3cfeabb97cdd93b3ddd294fc3384701db3dcfdc")'
RUN Rscript -e 'remotes::install_github("RinteRface/bs4Dash@5dfbc155d8f32f4d5e0f27aee2740da295f2ffe0")'
RUN Rscript -e 'remotes::install_github("dreamRs/shinyWidgets@330550cf7c53beb2ae51be15f4e1eccc1b7a50cf")'
RUN Rscript -e 'remotes::install_github("CIP-RIU/brapi@5f2a5caa48d72e2412ead128b9143cc1882a060c")'
RUN Rscript -e 'remotes::install_github("JohnCoene/waiter@a5c3f7d206b69e84b900b1eb64a94dae89ec764d")'
RUN mkdir /build_zone
ADD . /build_zone
WORKDIR /build_zone
RUN R -e 'remotes::install_local(upgrade="never")'
EXPOSE 3838
CMD  ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0');MrBean::run_app()"]
